### ISSUE TITLE
Updated minedojo example

### ISSUE THREAD

**Issue by roger-creus** [Eclectic-Sheep/sheeprl#270]
Hi!

It's my first time trying to use sheeprl, and I'm interested in using it with MineDojo. After installing all the dependencies, I still get errors with both Dreamerv2 and Dreamerv3:

For instance, when running: 
`xvfb-run python sheeprl.py exp=dreamer_v3 fabric.devices=1 env=minedojo env.id=open-ended algo.cnn_keys.encoder=[rgb] algo.actor.cls=sheeprl.algos.dreamer_v3.agent.MinedojoActor`

I get:

```
sheeprl/sheeprl/algos/dreamer_v3/agent.py", line 916, in forward
mask["mask_destroy"][t, b] = mask["mask_destroy"].expand_as(logits)
RuntimeError: expand(torch.FloatTensor{[4, 392]}, size=[392]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
```

Could you share a working config example for both dreamer v2 and dreamer v3 pls? :)

Also, is there any plan to support PPO and other algorithms in MineDojo? I think that would be great! Would that imply only implementing a MineDojoActor for PPO?

Thank you!

**Comment by roger-creus** [comment]
Following up, is the [t,b] indexing [here](https://github.com/Eclectic-Sheep/sheeprl/blob/main/sheeprl/algos/dreamer_v2/agent.py#L645) intentional? it looks off.

**Comment by belerico** [comment]
Hi @roger-creus, than you for using SheepRL! Do you have any feedback on the library?
BTW, i'll look into the issue tomorrow asap.
Thank you for your patience.

**Comment by roger-creus** [comment]
Btw I think the `KeyError` problem only happens with `env.num_envs > 1`. With 1 env it seems to work although it might be very slow because I don't see a single value logged.

**Comment by belerico** [comment]
I was looking into that yesterdya but i had a problem installing MineDojo: i had to clone the repo and update a malmo `bundle.gradle` file following https://github.com/microsoft/malmo/issues/942.

> Btw I think the KeyError problem only happens with env.num_envs > 1

Exactly, I've noted the same. I''l try in the next few days with multiple envs

**Comment by roger-creus** [comment]
Yup! Same experience here with `build.gradle`. I solved it following [this comment](https://github.com/MineDojo/MineDojo/issues/113#issuecomment-1982363203). Looking forward to this! If you manage to solve it, I might work on enabling PPO+MineDojo compatibility

**Comment by michele-milesi** [comment]
Hi @roger-creus,
- The `task_specs.pop("prompt") KeyError: 'prompt'` error is due to a Minedojo problem, they remove the `prompt` key the first time the environment is created, so the second environment, does not find that key in their configuration dictionary.
- Instead the `KeyError: KeyError(124)` is a sheeprl problem

I created a branch (https://github.com/Eclectic-Sheep/sheeprl/tree/fix/minedojo) in which I fixed these two problems. There is also a configuration file as an example (`dreamer_v3_minedojo.yaml` in the `sheeprl/configs/exp`) that you can take a cue from.

Let me know if it works, thanks.

PS. Minedojo is a very heavy environment, resetting can take minutes. It may be that your experiment is slower than others run with other environments for this reason.
