### ISSUE TITLE
Issue regarding random seed

### ISSUE THREAD

**Issue by anthony0727** [Eclectic-Sheep/sheeprl#274]
Since most RL algorithms adopt stochastic policy,

random seed should also affect `torch.distribution`

therefore, setting `torch.manual_seed` somewhere might be needed?

One concern is, when it comes to distributed training, it's quite tricky to set seeds across child processes.

I will think about clean way to do this!

**Comment by belerico** [comment]
Hi @anthony0727, 
we already have something like that as you can see here: https://github.com/Eclectic-Sheep/sheeprl/blob/main/sheeprl%2Fcli.py#L178.
Moreover, we set the seed for the environments in every process so that every env in every process has an independent seed.
Do you have anything different in mind?

**Comment by anthony0727** [comment]
Oops I didn't notice that! Sorry for bothering!
