### ISSUE TITLE
dv3 Imagination notebook re-visited

### ISSUE THREAD

**Issue by anthony0727** [Eclectic-Sheep/sheeprl#285]
I can't find a button to reopen the issue,
regarding #272, I have two questions!

1) shouldn't initial `stochastic_state` be flattened s.t. 
```
stochastic_state = player.stochastic_state.view(1, 1, -1).clone()
```
in
```
    if i == initial_steps - imagination_steps - 1:
        stochastic_state = player.stochastic_state.clone()
        recurrent_state = player.recurrent_state.clone()
```

2) shouldn't 0.5 also be added to imagined reconstructed obs? s.t.
```
        step_data["rgb"] = rec_obs["rgb"].unsqueeze(0).detach().cpu().numpy() + 0.5
```
in
```
 # imagination step
        stochastic_state, recurrent_state = world_model.rssm.imagination(stochastic_state, recurrent_state, actions)
        # update current state
        imagined_latent_states = torch.cat((stochastic_state.view(1, 1, -1), recurrent_state), -1)
        rec_obs = world_model.observation_model(imagined_latent_states)
        step_data["rgb"] = rec_obs["rgb"].unsqueeze(0).detach().cpu().numpy()
```

**Comment by anthony0727** [comment]
3) Also -0.5 is missing here.
This is quite critical in the test phase.
```
                preprocessed_obs[k] = preprocessed_obs[k] / 255.0 - 0.5
```
in
```
 preprocessed_obs[k] = torch.as_tensor(v[np.newaxis], dtype=torch.float32, device=fabric.device)
            if k in cfg.algo.cnn_keys.encoder:
                preprocessed_obs[k] = preprocessed_obs[k] / 255.0 
        mask = {k: v for k, v in preprocessed_obs.items() if k.startswith("mask")}
```

**Comment by anthony0727** [comment]
With the changes above, now I got the desired performance & results!

**Comment by michele-milesi** [comment]
Hi @anthony0727,
1. The player has the stochastic state that is flattened, as you can see here: https://github.com/Eclectic-Sheep/sheeprl/blob/40035066a55b76fd9f9dc4d92ee5a749e079e6b1/sheeprl/algos/dreamer_v3/agent.py#L655 or https://github.com/Eclectic-Sheep/sheeprl/blob/40035066a55b76fd9f9dc4d92ee5a749e079e6b1/sheeprl/algos/dreamer_v3/agent.py#L686
2. You are right, the reconstructed observation should be incremented by 0.5
3. Same as `2.`, we modified Dreamer and these two modifications escaped us.
4. `+1` is correct because there is a mismatch between actions and latent states (due to the inclusion of the initial latent state in the buffer). The problem with `+1` is that the last action is the one in position `0`.

I will fix these problems as soon as possible, thanks for reporting these.

**Comment by belerico** [comment]
@anthony0727 @michele-milesi thank you both!
Effectively we save the `stochastic` and `recurrent` state that refers to the previous action instead of the one that has been generated

**Comment by michele-milesi** [comment]
Hi @anthony0727,
we created a branch for fixing this issue, can you check if it works? (https://github.com/Eclectic-Sheep/sheeprl/tree/fix/dv3-imagination-notebook)

Thanks
